added components async and added vuex
firework/sparklez pull request #58
Opened 2017-05-10 20:49 UTC by Wellington01

#56

2017-05-10 21:07 UTC, gabrielboliveira requested changes

2017-05-10 21:07 UTC, gabrielboliveira commented on src/App.vue
>              })
```js
return this.tables.filter(table => !this.tableFilter || table.indexOf(this.tableFilter) !== -1)
```

2017-05-10 21:07 UTC, gabrielboliveira commented on src/App.vue
>  } from 'lodash'
double check if you are using all these imports

2017-05-10 21:07 UTC, gabrielboliveira commented on src/app/component/explorer/query.vue
> +                <el-input type="textarea" :autosize="{ minRows: 10 }" placeholder="Execute Query" v-model="query"></el-input>
break into new lines

2017-05-10 21:07 UTC, gabrielboliveira commented on src/app/global/error.vue
> +       <i class="el-icon-circle-close"></i> Could not load component.
tabulation

2017-05-11 14:03 UTC, dbpolito commented on src/app/component/explorer/structure.vue
> +import ConnectionMixin from '../../../js/mixin/connection.js'
i think we have `~` alias, if not add it

2017-05-11 19:39 UTC, Wellington01 commented
changed

2017-05-11 20:38 UTC, merged