Connection improvements and bug fixes
firework/sparklez pull request #66
Opened 2017-06-16 15:10 UTC by 0liveira

Fixes:
* Connection data now is updating after changes on form.
* Added connection validation to go to main component.
* Select table fixed by @gabrielboliveira 
* Added default data(just not filling fields)
* Now if connection is ok also table is valid, load table data.

2017-06-16 15:18 UTC, gabrielboliveira commented on src/App.vue
> +                if (this.databases.includes(this.connection.database)) this.loadTables(this.connection.database)
```js
if (this.databases.includes(this.connection.database)) {
     this.loadTables(this.connection.database)
}
```

2017-06-20 20:33 UTC, wesleyhf requested changes

2017-06-20 20:33 UTC, wesleyhf commented on src/App.vue
> +                            .then(() => {
use only one tab

2017-06-20 20:33 UTC, wesleyhf commented on src/App.vue
> +                                return _isNumber(value) || _isNull(value) ?
put inline

2017-06-20 20:33 UTC, wesleyhf commented on src/App.vue
> +                return true
enter

2017-06-20 20:33 UTC, wesleyhf commented on src/App.vue
> +                    return true
enter

2017-06-20 20:39 UTC, gabrielboliveira requested changes

2017-06-20 20:39 UTC, gabrielboliveira commented on src/App.vue
> +            }
Please use lodash's [forEach](https://lodash.com/docs/#forEach)

2017-06-20 20:39 UTC, gabrielboliveira commented on src/App.vue
> +                                    `'${value}'`
```js
return _isNumber(value) || _isNull(value)
    ? value
    : `'${value}'`
```

2017-06-20 20:39 UTC, gabrielboliveira commented on src/App.vue
> +                .then(() => {
```js
this.testConnection().then(() => this.parseTestConnection())
```

2017-06-20 20:39 UTC, gabrielboliveira commented on src/app/component/explorer/index.vue
> +import Vue from 'vue'
You really need this import?

2018-01-08 12:52 UTC, merged